name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest

  docker:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub / ACR
        run: echo "🔐 (We'll add login to ACR later)"

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Push to Docker Registry
        run: echo "🚀 (Push to registry logic here)"

      - name: Deploy to Staging VM
        run: echo "📦 SSH & deploy to staging logic here"

      - name: Manual approval for production
        uses: hmarr/auto-approve-action@v3.0.0
        if: always()  # We’ll replace this with manual approval job
