name: CI/CD Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest

  docker:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
         host: ${{ secrets.VM_IP }}
         username: ${{ secrets.VM_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
          docker stop my-python-app || true
          docker rm my-python-app || true
          docker pull my-python-app:latest || true  # If ACR was used
          docker run -d -p 80:8000 --name my-python-app my-python-app:latest

      # - name: Manual approval for production
      #   uses: hmarr/auto-approve-action@v3.0.0
      #   if: always()  # We’ll replace this with manual approval job
